### PR TITLE
HPCC4J-551 HPCCFile Make TLK Use Optional

### PR DESCRIPTION
**Pull request by jpmcmu**
- Added an option to HPCCFile to make TLK reading optional

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

### CODE REVIEW

**Review by rpastrana — COMMENTED** [review]
@jpmcmu looks good, but we need a corresponding junit test

**Comment by jpmcmu** [comment]
@rpastrana @drealeed  Added JUnit test. Note: current OOM test failure is due to OOM fixed merged into 9.2.x not having been up-merged to 9.4.x yet

**Review by rpastrana — APPROVED** [review]

**Comment by drealeed** [comment]
@rpastrana and @jpmcmu , can this be merged as soon as you have a chance to review and approve? It's blocking prod testing for data vault in the cloud.

**Comment by rpastrana** [comment]
@drealeed merged. Keep in mind, this is just a work-around.

**Pull request merged**
