### PR TITLE
JAPI-338 Provide mechanism to fetch based on a collection of fpos values

### PR DESCRIPTION
**Pull request by jpmcmu**
- Updated FieldType to track FilePosition type
- Updated ECL record translation code to add vinit to FilePositions
- Added code to handle FilePosition in BinaryRecordReader / Writer
- Added support for batch fetch requests to RowServiceInputStream
- Added HpccRandomAccessReader to allow for batch fetch requests
- Added JUnit test cases

Signed-off-by: James McMullan James.McMullan@lexisnexis.com
(cherry picked from commit bf506b726da5fc3623e742d5f54c7c849595329c)

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [X] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] I have performed unit tests to cover my changes.
  - [ ] I have performed system test and covered possible regressions and side effects.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

### CODE REVIEW

**Comment by jpmcmu** [comment]
@rpastrana please review

**Review by rpastrana — APPROVED** [review]
@jpmcmu looks good. just a couple of very minor comments/questions.

**Review by rpastrana — APPROVED** [review]

**Comment by rpastrana** [comment]
@jpmcmu approved, but should rebase and retarget 8.0.x

**Comment by jpmcmu** [comment]
@rpastrana closing. History in this branch doesn't match my local after rebasing not sure why that occurred. Reopening based on a corrected branch

**Pull request closed without merging**
