### PR TITLE
HPCC4J-672 Include hpcc-spark source code into the hpcc4j project

### PR DESCRIPTION
**Pull request by Michael-Gardner**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x] I have created a corresponding JIRA ticket for this submission
- [x] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ ] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
This is just adding spark-hpcc:master source code to the hpcc4j/spark-hpcc directory.  Working on fixing the pom and getting local builds  working in a second pull request for HPCC4J-673

**Comment by rpastrana** [comment]
@Michael-Gardner Looks good. However, we realized this is a great opportunity to remove the top-level DataAccess directory. Can we move everything up a level and remove 'DataAccess'?

@jpmcmu what do you think about the /Examples folder? Where could we put that?

**Comment by Michael-Gardner** [comment]
Agreed. My 673 PR moves the code from spark-hpcc/DataAccess over to spark-hpcc with examples alongside. Then fixes all the poms so that spark-hpcc is a module of the top level poms project.

**Comment by jpmcmu** [comment]
@rpastrana @Michael-Gardner I think the Examples folder can hang out in the Spark-HPCC folder for now. If we need to move it later that will be easy todo

**Pull request closed without merging**
