### PR TITLE
HPCC4J-513 Protect javax.xml.parsers.DocumentBuilder Parse calls

### PR DESCRIPTION
**Pull request by rpastrana**
- Synchronizes xml parse calls
- Adds corresponding junit tests

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x] I have created a corresponding JIRA ticket for this submission
- [x] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [x] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

### CODE REVIEW

**Comment by rpastrana** [comment]
@jpmcmu please review. 
Keep in mind, the wsclients should be shared via wsclient.get(wsclienttype) , but we can synchronize the rotect javax.xml.parsers.DocumentBuilder Parse calls when determining HPCC versions and modes. at wsclient init time. Let's discuss

**Comment by jpmcmu** [comment]
@rpastrana looks good, we should definitely create tests for other services using the multithreaded test here as a template.

**Comment by rpastrana** [comment]
> @rpastrana looks good, we should definitely create tests for other services using the multithreaded test here as a template.

@jpmcmu please review latest changes.

**Comment by jpmcmu** [comment]
@rpastrana looks good

**Pull request merged**
