### PR TITLE
HPCC4J-614 WsStore IPT invalid character tests

### PR DESCRIPTION
**Pull request by rpastrana**
- Adds new WsStore tests based on values which include IPT attribute delimiters
- Fixes issue noticed in wsstoreclient

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x] I have created a corresponding JIRA ticket for this submission
- [x] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [x] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

### CODE REVIEW

**Review by jpmcmu — APPROVED** [review]
@rpastrana looks good to me, only question I have is related to characters in the username. I vaguely remember that you had said that special characters in the username might cause problems, do we need a test case for that as well?

**Comment by rpastrana** [comment]
> @rpastrana looks good to me, only question I have is related to characters in the username. I vaguely remember that you had said that special characters in the username might cause problems, do we need a test case for that as well?

Yes, thanks for reminding me. The challenge is changing the user name only for this test...

**Comment by rpastrana** [comment]
This PR is dependent on HPCC-Platform changes: https://github.com/hpcc-systems/HPCC-Platform/pull/18763

**Comment by rpastrana** [comment]
@jpmcmu please review the latest commit

**Review by jpmcmu — APPROVED** [review]
@rpastrana looks good

**Comment by rpastrana** [comment]
Cannot merge before this:  https://github.com/hpcc-systems/HPCC-Platform/pull/18763

**Comment by rpastrana** [comment]
closing in favor of https://github.com/hpcc-systems/hpcc4j/pull/725

**Pull request closed without merging**
