### PR TITLE
HPCC4J-477 Ensure DZ paths contain trailing slash > 7.12.98

### PR DESCRIPTION
**Pull request by rpastrana**
- Provide utilities to ensure trailing slash on a given path string
- Provide junit for ensure trailing slash utility
- Ensure all DZ paths acquired from hpcc >= 7.12.98 contain trailing slash
- Provide DZ path junit

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x] I have created a corresponding JIRA ticket for this submission
- [x] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [x] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

### CODE REVIEW

**Comment by rpastrana** [comment]
@jpmcmu please review

**Review by jpmcmu — APPROVED** [review]
@rpastrana looks good

**Comment by jpmcmu** [comment]
@rpastrana Looks good, it does seem like we need to figure out a global method to handle the separators, but if I am understanding correctly this isn't something we can do it atm.

**Comment by rpastrana** [comment]
> @rpastrana Looks good, it does seem like we need to figure out a global method to handle the separators, but if I am understanding correctly this isn't something we can do it atm.

Well the remote DZ path separator has to communicated to the client. As far as I can tell we have to infer the separator from the "isLinux" response field. I'm not sure if that addresses your concern... but remember the path is not local so the client cannot assume it uses the local file system separator.

**Pull request merged**
