### PR TITLE
HPCC4J-501 Deploy artifacts via github action

### PR DESCRIPTION
**Pull request by jpmcmu**
- Added a new github action workflow to publish builds on release tag

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ ] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

### CODE REVIEW

**Review by rpastrana — APPROVED** [review]
@jpmcmu seems reasonable pending @Michael-Gardner 's review.

However, shouldn't this target 9.0.x? Mike please let us know.

**Review by rpastrana — APPROVED** [review]
@jpmcmu seems reasonable pending @Michael-Gardner 's review.

However, shouldn't this target 9.0.x? Mike please let us know.

**Comment by GordonSmith** [comment]
@jpmcmu - is 9.2.x or 9.0.x appropriate?

**Comment by rpastrana** [comment]
I think the plan is to migrate all 9.0.+ builds from Jenkins, @Michael-Gardner please confirm

**Comment by jpmcmu** [comment]
@rpastrana @GordonSmith Yep, you are correct it probably should go into 9.0.x, will rebase.

**Pull request merged**
