### PR TITLE
HPCC4J-644 FileUtilityTest atomic record count false sharing

### PR DESCRIPTION
**Pull request by jpmcmu**
- Fixed false sharing on atomic counter in FileUtility

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [X] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

### CODE REVIEW

**Comment by jpmcmu** [comment]
@ghalliday @mckellyln  Atomic counter fix. Note: FileUtility is a debugging utility, doesn't affect end user code

**Review by rpastrana — APPROVED** [review]
@jpmcmu this looks like a sensible fix based on the offline explanation you provided on the atomic increment issue.

**Comment by jpmcmu** [comment]
Background information on the issue regarding the atomics:

Atomics are fast as long as the cache line that is storing that atomic is in the CPU core's local cache, but when running with a bunch of threads each CPU core first has to request that cache line be moved to their local core's cache before it can be incremented. The end result is each thread is waiting around for that cache line to be moved their core so they can increment it. The result of this false sharing is a problem a lot like lock contention even though atomics are lockless.

**Comment by rpastrana** [comment]
> Background information on the issue regarding the atomics:
> 
> Atomics are fast as long as the cache line that is storing that atomic is in the CPU core's local cache, but when running with a bunch of threads each CPU core first has to request that cache line be moved to their local core's cache before it can be incremented. The end result is each thread is waiting around for that cache line to be moved their core so they can increment it. The result of this false sharing is a problem a lot like lock contention even though atomics are lockless.

Thanks for tracking this down @jpmcmu

**Comment by jpmcmu** [comment]
@rpastrana retargeted to 9.6.x

**Pull request merged**
